language: julia
os:
  - linux
  - osx
julia:
  - 0.4
notifications:
  email: false
script:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - julia --check-bounds=yes -e 'Pkg.clone("https://github.com/garrison/Bravais.jl.git"); Pkg.clone(pwd()); Pkg.build("ExactDiag"); Pkg.test("ExactDiag"; coverage=true)'
after_success:
  - julia -e 'cd(Pkg.dir("ExactDiag")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
