language: julia
os:
  - linux
  - osx
julia:
  - 1.0
  - 1.1
  - nightly
matrix:
  allow_failures:
    - julia: nightly
notifications:
  email: false
addons:
  apt:
    packages:
    - hdf5-tools
git:
  depth: 99999999
before_script:
  - julia -e 'import Pkg; Pkg.clone("https://github.com/garrison/Bravais.jl.git")'
coveralls: true
