language: julia
os:
  - linux
  - osx
julia:
  - 0.6
  - nightly
notifications:
  email: false
git:
  depth: 99999999
before_script:
  - julia -e 'Pkg.clone("https://github.com/garrison/Bravais.jl.git")'
after_success:
  - julia -e 'cd(Pkg.dir("ExactDiag")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
