language: julia
os:
  - linux
  - osx
julia:
  - 0.6
  - nightly
notifications:
  email: false
git:
  depth: 99999999
script:
  - julia -e 'Pkg.clone("https://github.com/garrison/Bravais.jl.git"); Pkg.clone(pwd()); Pkg.build("ExactDiag"); Pkg.test("ExactDiag"; coverage=true)'
after_success:
  - julia -e 'cd(Pkg.dir("ExactDiag")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
